PIPELINE_NAME = "NetworkSecurity"
ARTIFACT_DIR = "artifact"

DATA_INGESTION_INGESTED_DIR = "ingested"
DATA_INGESTION_DIR_NAME = "data_ingestion"
DATA_INGESTION_FEATURE_STORE_DIR = "feature_store"

DATA_INGESTION_TRAIN_TEST_SPLIT_RATIO = 0.2

DATA_INGESTION_COLLECTION_NAME = "NetworkData"
DATA_INGESTION_DATABASE_NAME = "Anurag"

FILE_NAME = "phishingData.csv"

TRAIN_FILE_NAME = "train.csv"
TEST_FILE_NAME = "test.csv"